### PR TITLE
assign efs volumes configuration to efs_volume variable in ecs_alb_se…

### PR DESCRIPTION
**Pull request by oajara**
## what
Creates a separated variable for EFS volumes.

## why
* The way **terraform-aws-ecs-web-app** [defines](https://github.com/cloudposse/terraform-aws-ecs-web-app/blob/master/variables.tf#L220-L244) and [uses](https://github.com/cloudposse/terraform-aws-ecs-web-app/blob/master/main.tf#L165) the EFS volumes with the  [terraform-aws-ecs-alb-service-task](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task) module is not working correctly and the EFS volume is not being set in the resulting task definition.
* By separating EFS volumes and Docker volumes they can be assigned to the [docker_volumes](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/master/variables.tf#L286) and [efs_volumes](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/master/variables.tf#L286) as expected by the module.

### CODE REVIEW

**Comment by jamengual** [comment]
This is a breaking change.
You are modifying an existing variable and dissecting it into two which is not backward compatible.

I can see what was done in the [terraform-aws-ecs-alb-service-task](https://github.com/cloudposse/terraform-aws-ecs-alb-service-task) so I guess it is ok to replicate this over to here.

**Comment by jbcom** [comment]
I just pushed https://github.com/cloudposse/terraform-aws-ecs-web-app/pull/213 which maintains backwards compatibility and adds support for FSX volumes.

**Pull request closed without merging**
