### PR TITLE
Add option to include NLB ingress rule

### PR DESCRIPTION
**Pull request by jhosteny**
This PR is related to https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/pull/44, and exposes the options added there at the application level.

### CODE REVIEW

**Comment by aknysh** [comment]
@jhosteny thanks again!
Did you run this module with CodePipeline/CodeBuild enabled?
Our Terratest throws error on your PR (although I'm sure it has nothing to do with your changes):

```
TestExamplesComplete 2020-01-21T20:51:13Z command.go:121:                                                                                                                                
TestExamplesComplete 2020-01-21T20:51:13Z command.go:121: Error: Error creating CodeBuild project: InvalidInputException:                                                                
TestExamplesComplete 2020-01-21T20:51:13Z command.go:121:                                                                                                                                
TestExamplesComplete 2020-01-21T20:51:13Z command.go:121:   on /codefresh/volume/terraform-aws-ecs-web-app/test/src/.terraform/modules/ecs_web_app.ecs_codepipeline.codebuild/main.tf lin
e 169, in resource "aws_codebuild_project" "default":                                                                                                                                    
```

Not sure what could be the issue, need to take a look (the test ran OK 6 days ago on another PR).

Thanks

**Comment by jhosteny** [comment]
Hi @aknysh, thanks for looking at this!

I did not run with CodeBuild / CodePipeline enabled. It looks like [the provider](https://github.com/terraform-providers/terraform-provider-aws/issues/11642) may be the culprit?

**Comment by aknysh** [comment]
> Hi @aknysh, thanks for looking at this!
> 
> I did not run with CodeBuild / CodePipeline enabled. It looks like [the upstream SDK for the provider](https://github.com/terraform-providers/terraform-provider-aws/issues/11642) may be the culprit?

Looks like it, thanks @jhosteny

**Comment by aknysh** [comment]
@jhosteny  they merged the PR and said they would release anew aws provider tomorrow.
Will run test again.

**Comment by jhosteny** [comment]
Hi @aknysh, the provider has been [updated](https://github.com/terraform-providers/terraform-provider-aws/tree/v2.46.0). I believe this should work now.

**Pull request merged**
