### PR TITLE
chore: add load_balancing_algorithm_type variable

### PR DESCRIPTION
**Pull request by dmitrijn**
## what

- add load_balancing_algorithm_type variable for alb-ingress module

## why

- allow to switch between round_robin and least_outstanding_requests for alb target groups

### CODE REVIEW

**Comment by Gowiem** [comment]
@dmitrijn mind looking into the various failures?

**Comment by dmitrijn** [comment]
@Gowiem please run tests

**Comment by dmitrijn** [comment]
@Gowiem it's not possible to run tests on terraform v5 provider. If i will update all modules it will break compatibility with v3 provider and old terraform versions < 1.0.0

**Comment by Gowiem** [comment]
@dmitrijn we do want to move towards 1.0.0 -- I would say we pull the band aid off now. If you don't want to sign up for that as part of this PR, then that is understandable, but it will block this PR. 

I will surface this conversation in our maintainer slack channel. Thanks for bringing it up!

**Comment by goruha** [comment]
Resolved conflicts

**Review by goruha — APPROVED** [review]

**Review by osterman — APPROVED** [review]

**Comment by goruha** [comment]
@dmitrijn Merged.
Thanks for your contribution

**Pull request merged**
