### PR TITLE
Updating module dependencies

### PR DESCRIPTION
**Pull request by jamengual**
## what
* Updating all module dependencies

## why
* Improved module options
* Added fix for github provider regresion

## references
* https://github.com/terraform-providers/terraform-provider-github/pull/464

### CODE REVIEW

**Comment by nitrocode** [comment]
Not sure why the tests are failing...

**Comment by jhosteny** [comment]
It looks like `nuke` needs to be run before this can pass again. #52 is also a duplicate of this, which I will close once this passes.

**Comment by jamengual** [comment]
> Change in variable names can break user code, Let's hope they use versioning properly

This was caused by an upstream module change, I'm not going to merge until we have a decision on that

**Comment by jhosteny** [comment]
Hi @jamengual, can you clarify what you are waiting on before merging?

**Comment by jamengual** [comment]
> Hi @jamengual, can you clarify what you are waiting for before merging?

There are upstream changes that forced this PR to change input values, I was hoping to revert back those changes since inadvertently are affecting this and other modules but I could merge this and open another PR, I'm open to suggestions

**Comment by jhosteny** [comment]
> There are upstream changes that forced this PR to change input values, I was hoping to revert back those changes since inadvertently are affecting this and other modules but I could merge this and open another PR, I'm open to suggestions

Right, I didn't see what input values changed aside from the `mount_points` default type (which was the same at the prior module for container definitions)?

**Comment by jamengual** [comment]
> Right, I didn't see what input values changed aside from the `mount_points` default type (which was the same at the prior module for container definitions)?

https://github.com/cloudposse/terraform-aws-ecs-web-app/pull/53/files#diff-02ad70b8a118d59ac14f9a8bdf408999R71

**Comment by jhosteny** [comment]
Ah, I saw the output change. I thought you meant there was an upstream variable change for one of the modules used by this module.

Personally, I would not mind updating my app when I changed the tag to reference `ecr_repository_url`. Though the name is different, the functionality and semantics are the same. It seems like that is the correct name anyway, and it is probably more intuitive to use the module if those match each other, and the AWS docs and terrform resource. But, if you wanted to avoid this, perhaps you can revert the output name reported by this module to `ecr_registry_url` (even though it gets `ecr_repository_url` from the referenced ECR module)?

Do the modules ever get a major version bump? I probably have not seen enough of them to know if that is done. I suppose that is the other consideration.

**Comment by jamengual** [comment]
> Ah, I saw the output change. I thought you meant there was an upstream variable change for one of the modules used by this module.
> 
> Personally, I would not mind updating my app when I changed the tag to reference `ecr_repository_url`. Though the name is different, the functionality and semantics are the same. It seems like that is the correct name anyway, and it is probably more intuitive to use the module if those match each other, and the AWS docs and terrform resource. But, if you wanted to avoid this, perhaps you can revert the output name reported by this module to `ecr_registry_url` (even though it gets `ecr_repository_url` from the referenced ECR module)?
> 
> Do the modules ever get a major version bump? I probably have not seen enough of them to know if that is done. I suppose that is the other consideration.

good point, will do

**Comment by osterman** [comment]
> Do the modules ever get a major version bump? I probably have not seen enough of them to know if that is done. I suppose that is the other consideration.

@jhosteny we're deliberately sticking with `0.x`

See: https://docs.cloudposse.com/community/faq/#when-do-we-cut-new-releases

**Comment by osterman** [comment]
> Change in variable names can break user code, Let's hope they use versioning properly

@brcnblc since we're `0.x` we are permitted to change anything at anytime =) while we try to maintain stability, interfaces are not yet stable in all cases.

**Pull request merged**
