### PR TITLE
add option for ecs managed tags

### PR DESCRIPTION
**Pull request by Zaargh**
## what
* Expose options to `propagate_tags` and `enable_ecs_managed_tags`, available in `cloudposse/ecs-alb-service-task/aws` child module

## why
* By default the child module disables Amazon ECS managed tags for the tasks within the service
* This behavior makes it difficult to manage costs - they show  as untagged in the Cost explorer

### CODE REVIEW

**Review by max-lobur — APPROVED** [review]
This makes sense.
Thank you for your contribution!

**Comment by nitrocode** [comment]
@Zaargh You'll need to add an empty commit here due to `validate-codeowners` action not running correctly.

**Comment by Zaargh** [comment]
> @Zaargh You'll need to add an empty commit here due to `validate-codeowners` action not running correctly.

done

**Comment by nitrocode** [comment]
@Zaargh you need to add an empty commit and push up the code or the `validate-codeowners` will not run

**Comment by nitrocode** [comment]
@Zaargh perhaps run another empty commit ? Unsure why the validate-codeowners hasn't rerun.

**Comment by Zaargh** [comment]
@nitrocode from what I see, it needs approval from a maintainer to run. I can add another empty commit if you think that's not it. 
image
image

**Review by nitrocode — APPROVED** [review]

**Pull request merged**
