### PR TITLE
Update Terraform cloudposse/ecs-codepipeline/aws to v0.33.0

### LINKED ISSUE #227: Bump  terraform-aws-ecs-codepipeline to v0.32.0
### Describe the Bug

Apple Silicon machines result in the below error.

```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/github v3.0.0 does not have a
│ package available for your current platform, darwin_arm64.
```

### Expected Behavior

That it would pull down successfully

### Steps to Reproduce

`terraform init` on an Apple Silicon machine

Note: the issue does not replicate on a `linux_arm64` target.

### Screenshots

_No response_

### Environment

- Apple M1
- macOS Ventura - 13.2.1

### Additional Context

It would appear the `hashicorp/github` version has been pinned to `3.0.0` for some time in `cloudposse/repository-webhooks/github`. `cloudposse/repository-webhooks/github` is a dependency of `cloudposse/ecs-codepipeline/aws`. This was updated two weeks ago, and `cloudposse/ecs-codepipeline/aws` was also updated. Links to the tags are below.

The targeted version should be updated to `v0.32.0`

https://github.com/cloudposse/terraform-github-repository-webhooks/releases/tag/0.13.0

https://github.com/cloudposse/terraform-aws-ecs-codepipeline/releases/tag/0.32.0

https://github.com/cloudposse/terraform-aws-ecs-web-app/blob/044a9e671ed3b8085238375358309fe173edf5e8/main.tf#L189-L192

### PR DESCRIPTION
**Pull request by adamantike**
# Breaking changes

This release introduces a breaking change that affects projects using the `github_webhooks_token` variable.

Since Terraform 1.2.0, modules to be used with the `for_each`, `count`, and `depends_on` arguments must not contain their own provider configurations. The `github_webhooks_token` variable was being used to instantiate a [`github` provider](https://registry.terraform.io/providers/integrations/github/latest/docs), which must now be instantiated and provided separately.

If your project is affected by this change, the following steps will allow you to upgrade to this version:

1. Add the GitHub provider to your project:
    ```hcl
    terraform {
      required_providers {
        github = {
          source  = "integrations/github"
          version = ">= 4.2.0"
        }
      }
    }
    ```

1. Instantiate the provider (feel free to use any other supported [Authentication mechanism](https://registry.terraform.io/providers/integrations/github/latest/docs#authentication)):
    ```hcl
    provider "github" {
      owner = var.repo_owner
      token = "{your_github_token}"
    }
    ```

1. Stop providing the `github_webhooks_token` variable to this module.

## what

* Removed variables no longer available in the `cloudposse/ecs-codepipeline/aws` module.
* Supersedes #202
* Fixes #227

## why
* Version 0.32.0 upgrades the `cloudposse/repository-webhooks/github` module, which removed the hardcoded `github` provider, so some variables have been removed in favor of instantiating the provider separately.

## references
* Upstream issue: https://github.com/cloudposse/terraform-github-repository-webhooks/issues/37
* Upstream pull request: https://github.com/cloudposse/terraform-github-repository-webhooks/pull/40

### CODE REVIEW

**Comment by getglad** [comment]
@Gowiem @korenyoni - is it possible to get this reviewed or landed? Would be helpful to have this in `main`

**Comment by Gowiem** [comment]
Pulling in @joe-niland since he's an expert on this module. Joe, figured you may have an opinion here.

**Comment by Gowiem** [comment]
@adamantike @getglad -- This looks like a solid contribution, thanks! I'm checking with the rest of the maintainer team on if this should be a major version rev or not. I believe it should, but semver is followed differently everywhere and it's we've just started rev'ing past v0.x.y, so it's good to check. Will follow up when we can move this forward 👍

**Comment by joe-niland** [comment]
> Pulling in @joe-niland since he's an expert on this module. Joe, figured you may have an opinion here.

Thanks for the ping @Gowiem.
I don't use this module that much anymore, but I did test this branch and it was fine after I made the adjustments below.

Since this introduces  a breaking change, I think we need to include information about how to change a consuming module in the PR description ([example](https://github.com/cloudposse/terraform-aws-s3-bucket/pull/158)). As far as I can see, it's just:
- unsetting the `github_webhooks_token` variable
- adding a `github` provider block 
- updating the `github` provider source and version

**Comment by Gowiem** [comment]
@joe-niland good call on the breaking changes info and including that in the PR description. @adamantike do you mind providing that info into your description and then we'll get this merged and cut a release? Here is a great PR example of what that should look like: https://github.com/cloudposse/terraform-aws-s3-bucket/pull/158

**Comment by mihaiplesa** [comment]
Looking forward to get this in which would fix the below.
```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/github v3.0.0 does not have a
│ package available for your current platform, darwin_arm64.
```

**Comment by getglad** [comment]
@max-lobur @Gowiem @joe-niland friendly re-bump on this.

It sounds like this was down to documentation on the PR description, but now seeing some failures around a pinning to `https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2` in a subnet module.

Any ideas on how we can get it unblocked and merged?

**Comment by adamantike** [comment]
Sorry for not tackling this before. I have rebased my changes, and updated the PR description to include the information about the breaking change and how to upgrade to the new minor version!

**Comment by Gowiem** [comment]
@adamantike sorry to continue to drag this out, but we've got some lint issues and terraform failures due to the `moved` block somewhere in the chain. The `moved` block means we need to update the required terraform version in either the module itself or in the examples directories. Mind checking into those and we'll see if we can get this PR green and shipped?

**Comment by adamantike** [comment]
It's probably the same issue I needed to fix in the complete example, because of very old versions of `dynamic-subnets` and `vpc` modules being used. Let me try to fix those ASAP.

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
@adamantike can you bump this line to v1.3+? https://github.com/cloudposse/terraform-aws-ecs-web-app/blob/main/examples/complete/versions.tf#L2

**Comment by adamantike** [comment]
Just updated `required_version` in the examples to use at least 1.1.0, as that's the minimum required version in the `dynamic-subnets` module ([reference](https://github.com/cloudposse/terraform-aws-dynamic-subnets/blob/ec00f4559a8ed973a22325c963f9cf4c7fac1da6/versions.tf#L2))

**Comment by Gowiem** [comment]
The fun never ends: 

```
│ Error: Unsupported block type
│ 
│   on .terraform/modules/ecs_web_app.ecs_codepipeline.codebuild/main.tf line 414, in resource "aws_codebuild_project" "default":
│  414:     dynamic "auth" {
│ 
│ Blocks of type "auth" are not expected here.
```

Mind looking into that @adamantike?

**Comment by adamantike** [comment]
That error will require more coordination with other modules. The issue is that `cloudposse/terraform-aws-codebuild` uses `source.auth` dynamic blocks ([reference](https://github.com/cloudposse/terraform-aws-codebuild/blob/dac7df9798eb4e7211e45c182f1b5a46c5218ae4/main.tf#L414-L420)), which were removed from the AWS provider version 5 ([notes from the upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-5-upgrade#resourceaws_codebuild_project)).

I'm not familiar with how well maintained that module is, but consider that it has an [open issue](https://github.com/cloudposse/terraform-aws-codebuild/issues/104) and two open PRs ([1](https://github.com/cloudposse/terraform-aws-codebuild/pull/106), [2](https://github.com/cloudposse/terraform-aws-codebuild/pull/113)) from 2022, regarding better support for AWS provider version 4.

A temporary fix would be to limit the AWS provider in this module, to: `version = ">= 3.34, < 5.0"`. That will unfortunately affect users that don't even use CodePipeline. Is there any better option to apply in the meantime?

**Comment by adamantike** [comment]
I have created https://github.com/cloudposse/terraform-aws-codebuild/pull/123, in case we want to go with the upstream fix. It will require releasing a new version for `cloudposse/codebuild/aws` and `cloudposse/ecs-codepipeline/aws`, to then refresh this PR.

**Comment by Gowiem** [comment]
@adamantike I think going with the option of limiting to `> 5.0.` AWS Provider is legit in this circumstance. At least until we get your other PR upstream in and then we can circle back around to this module, if that is of interest. 

Want to make that update within `versions.tf` and we'll see how the tests do?

**Comment by Gowiem** [comment]
@adamantike sorry to do it, mind running `make init && make readme` + commit that?

**Comment by Gowiem** [comment]
@adamantike haha this is hitting every bump in the road, I'm sorry. This is why large child modules like this aren't the best... but they do have their place so here we are. 

Anyway, try bumping the ALB module to the latest tag (`1.7.0`): https://github.com/cloudposse/terraform-aws-ecs-web-app/blob/main/examples/complete/main.tf#L29C1-L30

**Comment by adamantike** [comment]
Yeah, it seems these examples haven't been tested by the CI in a while. But we will figure it out!

The PR is already using the latest version for the ALB module, so I will need to investigate if this is related to the S3 ACL defaults being changed by AWS last month.

**Comment by adamantike** [comment]
After debugging the current issue, I have found that we need to avoid the example from trying to create ACLs for the ALB's access logs bucket.

There are two options here, from simpler to more complex:
1. Change the example to set `access_logs_enabled = false` when instantiating the ALB module.
2. Send `s3_object_ownership = "BucketOwnerEnforced` to the underlying `cloudposse/s3-bucket/aws` module, which disables the ACL creation ([reference](https://github.com/cloudposse/terraform-aws-s3-bucket/blob/3.1.1/main.tf#L160)). This requires:
  a. Exposing that variable in `cloudposse/lb-s3-bucket/aws` and release a new version. I have already created a PR for this: https://github.com/cloudposse/terraform-aws-lb-s3-bucket/pull/67
  b. Expose the same variable, and bump the `cloudposse/lb-s3-bucket/aws` module, in `cloudposse-aws-alb`.
  c. Bump `cloudposse-aws-alb` in this module's examples, and set `s3_object_ownership = "BucketOwnerEnforced`.

**Comment by hans-d** [comment]
@adamantike hi, can you update this pr so that all tests pass? otherwise this PR  will be closed due to staleness. thanks!

**Comment by kevcube** [comment]
@hans-d this is a quite important PR as its the only blocker for M1 compatibility of this module. I’m taking it over to see if I can get tests passing

**Review by kevcube — APPROVED** [review]

**Review by gberenice — APPROVED** [review]

**Pull request merged**
