### PR TITLE
Fix example in README.md

### PR DESCRIPTION
**Pull request by Appelberg-s**
## what
* The example provided in the README.md gave an error when trying to run it since it set the attribute `environment` when it was probably trying set the attribute `container_environment`.

### CODE REVIEW

**Comment by Nuru** [comment]
@Appelberg-s Thank you for your contribution.

In Cloud Posse's repos, `README.md` is usually a generated file. You need to make your change in `README.yaml` which is the main source for generating `README.md`. 

After making changes to `README.yaml` (and assuming you have Docker installed) you can run:
- `make init`
- `make pr/auto-format`

to generate the `README.md` and other documentation. Then check in and push the changed files and you should be good to go.

**Review by Nuru — CHANGES_REQUESTED** [review]
Make changes to `README.yaml` not `README.md`

**Comment by Appelberg-s** [comment]
Thanks for the feedback! Made the suggested changes in the latest commit.

**Review by nitrocode — DISMISSED** [review]

**Comment by jamengual** [comment]
> Thanks for the feedback! Made the suggested changes in the latest commit.

you need to revert back the README.md and only leave your changes in the README.yaml and run : 
```
make init
make github/init
make readme
```

**Review by jamengual — APPROVED** [review]

**Pull request merged**
