### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by dknell**
## what
* Bump the dependencies to the latest versions

## why
* Keep modules up-to-date and pull in the latest fixes

### CODE REVIEW

**Comment by jamengual** [comment]
@dknell please look at the failed test, looks like the ecr module updates require a new variable to be set for a dynamic.

**Comment by joe-niland** [comment]
@dknell please change all version pinning to lower bound, and also rebase from master.

**Comment by joe-niland** [comment]
Fixed in #78

**Pull request closed without merging**
