### PR TITLE
feat: expose additional OIDC scope settings

### PR DESCRIPTION
**Pull request by jhosteny**
## what
* Updates dependency on https://github.com/cloudposse/terraform-aws-alb-ingress module for OIDC scope
* Exposes OIDC scope settings for web application

## why
* Allow the providers' default OIDC scopes to be expanded upon

## references
* https://github.com/cloudposse/terraform-aws-alb-ingress/pull/35

### CODE REVIEW

**Review by jamengual — DISMISSED** [review]

**Comment by jamengual** [comment]
@jhosteny did you happen to modify the readme? all test are passing except for the auto-rebuild readme and it seems there are some missing lines

**Comment by jhosteny** [comment]
Hi @jamengual, I did regenerate the README, but I had a stale build harness. I updated that, fixed the README, and pushed. I expect it should pass shortly.

**Review by aknysh — APPROVED** [review]
thanks @jhosteny

**Pull request merged**
