### PR TITLE
Terraform 0.14 upgrade

### PR DESCRIPTION
**Pull request by maximmi**
## what
- Upgrade to support Terraform 0.14 and bring up to current Cloud Posse standard

## why
- Support Terraform 0.14
- supersedes and closes #83 

blocked by https://github.com/cloudposse/terraform-aws-ecs-codepipeline/pull/54/files

### CODE REVIEW

**Comment by adamantike** [comment]
@maximmi, is there anything blocking this PR from being merged?

**Comment by jhosteny** [comment]
> @maximmi, is there anything blocking this PR from being merged?

I think this is blocked by https://github.com/cloudposse/terraform-aws-ecs-codepipeline/pull/54/files, and then also needs an update on the version for the `ecs_cloudwatch_autoscale` module, which has been updated for 0.14 support.

**Review by osterman — DISMISSED** [review]

**Review by osterman — APPROVED** [review]

**Comment by jross-ai** [comment]
Is there an ETA for when this is going to get merged in?

**Review by osterman — APPROVED** [review]

**Comment by maximmi** [comment]
@adamantike @jhosteny @jross-ai  here is new release: https://github.com/cloudposse/terraform-aws-ecs-web-app/releases/tag/0.48.0

thank you all for contribution

**Pull request merged**
