### PR TITLE
feat: update terraform-aws-ecs-codepipeline dependency

### PR DESCRIPTION
**Pull request by jhosteny**
## what
* Plumbed the `github_anonymous` variable from the https://github.com/cloudposse/terraform-aws-ecs-codepipeline/ module through this module as a variable

## why
* Allow modules using this one to run without codepipeline and the associated GitHub web hooks

## references
* Expose variable that was introduced by https://github.com/cloudposse/terraform-aws-ecs-codepipeline/commit/524844ca6911549f97cd8577b7612113694c05e8

### CODE REVIEW

**Comment by Gowiem** [comment]
@jhosteny Mind trying to pass `github_webhooks_anonymous = true` to the example/complete to see how that works out? We're having test failures if this module recently revolving around the codepipeline GH provider. Wondering if that will fix things...

**Comment by jhosteny** [comment]
Hi @Gowiem - I just added this. I'll keep an eye out for the next status check to see if there are further issues.

**Comment by Gowiem** [comment]
@jhosteny Ah sorry, gotta request another change -- Tests failed with: 

```
Error: If `anonymous` is true, `token` cannot be set.
```

Can you set the `token` variable to null?

**Comment by jhosteny** [comment]
Hi @Gowiem, I just pushed before your comment. I deleted it, but the default is an empty string. It looks like you just kicked the test off again, so I will wait to investigate if that needs to be explicitly `null`. Thanks for helping get this through.

**Comment by jhosteny** [comment]
@Gowiem this seems to be a different failure now. I'll be able to dig into it further after the weekend.

**Comment by Gowiem** [comment]
@jhosteny Yeah, that is unrelated to your work I believe. Those *might* be transient errors... as we've had a number of issues with S3 buckets in the past (though I'm not sure about the ALB issue). 

I'll fire off the terratests again and we'll see.

**Comment by Gowiem** [comment]
Huh seems to be recurring... Now I'm wondering if one of the terratest's `tf destory`s didn't properly remove all the resources for these tests. If that's the case, we have `aws-nuke` running against the CP test environment on a schedule so that should eventually sort itself out. Let's sync back up on this one in a few days.

**Comment by jhosteny** [comment]
@Gowiem thanks! I'll check back in later this week on it.

**Comment by jhosteny** [comment]
@jamengual arrgh. It looks like the provider was just tagged at 2.9.0 6 hours ago, and between 2.8.1 and 2.9.0, the anonymous setting was removed. I think the https://github.com/cloudposse/terraform-github-repository-webhooks module will need to be changed yet again to either set the pessimistic constraint operator to `~> 2.8.0`, or fixed to work with 2.,9+. I'm not sure why they removed that option in a minor release.

**Comment by osterman** [comment]
@jhosteny try rebasing... I think @jamengual has fixed tests on this module.

**Comment by jhosteny** [comment]
@osterman thanks. This PR is no longer needed, as the change was picked up in #53.

**Pull request merged**
