### PR TITLE
docs: add a required input to readme

### PR DESCRIPTION
**Pull request by ebi-yade**
## what

Just as shown in the code

## why

I copied, pasted, modified, and applied the code; then, I got an error.

## references

The input docs of the module thereof: https://github.com/cloudposse/terraform-aws-ecs-web-app#inputs

### CODE REVIEW

**Comment by ebi-yade** [comment]
Hello,

I don't know why but my commits have been reverted by the AutoFormat action.  Could you check what was wrong and correct them, if possible, please?

**Comment by jamengual** [comment]
Please do the changes on the doc to the Readme.yaml file instead.

**Comment by ebi-yade** [comment]
I got it, thanks!

**Comment by Gowiem** [comment]
@ebi-yade this PR is quite old and is a small change, so I'm inclined to close it. Please reopen and bring it up-to-date if it is still a change you would like to see. Thanks!

**Pull request closed without merging**
